baseURL = 'https://lnk-k.github.io/'
languageCode = 'zh-cn'
title = 'lnk-k 的博客'
copyright = '© lnk-k'
enableRobotsTXT = true
summaryLength = 90
timeZone = 'Asia/Shanghai'

[params]
  author = 'lnk-k'
  description = '记录记录一些记录'
  github = 'https://github.com/lnk-k'
  avatar = 'https://github.com/lnk-k.png'
  subtitle = '想想一些想'

[menus]
  [[menus.main]]
    name = '首页'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = '文章'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = '关于'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = '标签'
    url = '/tags/'
    weight = 40
  [[menus.main]]
    name = '分类'
    url = '/categories/'
    weight = 50
  [[menus.main]]
    name = '归档'
    pageRef = '/archives'
    weight = 60

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'github'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
