name: Deploy Hugo site

# 只要你往主分支（main）推源码，就会触发
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装带 extended 特性的 Hugo（可自动带 withdeploy 功能）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1'   # 或者选择最新版本

      # 3. 生成静态文件
      - name: Build the site
        run: hugo --minify

      # 4. 把 public/ 发布到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          publish_branch: main       # 你的 Pages 分支，一般是 main；若是 gh-pages 改成 gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
